//! Generated by capsule
//!
//! `main.rs` is used to define rust lang items and modules.
//! See `entry.rs` for the `main` function.
//! See `error.rs` for the `Error` type.

#![no_std]
#![no_main]

use ckb_std::{default_alloc, entry};


fn program_entry() -> i8 {
    // Call main function and return error code
    42
}


entry!(program_entry);
default_alloc!();
