[package]
name = "mithril"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.13.0"
mithril-stm = { version = "0.3.3", features = ["num-integer-backend"] }